language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/webhome.ino

install:
    - pip install -U platformio
    - platformio lib install 91
    - wget https://github.com/ToniA/arduino-heatpumpir/archive/master.zip -O /tmp/arduino-heatpumpir.zip
    - unzip /tmp/arduino-heatpumpir.zip -d /tmp

script:
    - platformio ci --lib="." --lib="/tmp/arduino-heatpumpir-master" --board=nanoatmega328
