language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/webhome.ino

install:
    - pip install -U platformio
    - platformio lib install 64 91 290
    - cp src/env.h.example src/env.h

script:
    - platformio ci --lib="." --board=esp01
